# Generated by Django 3.2.3 on 2021-05-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnixLinuxActFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discovered_os_name', models.CharField(blank=True, max_length=50, null=True)),
                ('host_osinstalltype', models.CharField(blank=True, max_length=100, null=True)),
                ('environment', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('operation_location_limited_to', models.CharField(blank=True, max_length=50, null=True)),
                ('externalstorage', models.CharField(blank=True, db_column='ExternalStorage', max_length=10, null=True)),
                ('os_description', models.CharField(blank=True, max_length=50, null=True)),
                ('host_osrelease', models.CharField(blank=True, max_length=20, null=True)),
                ('impact_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=250, null=True)),
                ('housing_only', models.CharField(blank=True, max_length=20, null=True)),
                ('backup', models.CharField(blank=True, max_length=10, null=True)),
                ('time_server', models.CharField(blank=True, max_length=200, null=True)),
                ('backup_environment', models.CharField(blank=True, max_length=50, null=True)),
                ('patch_group', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_owner', models.CharField(blank=True, max_length=50, null=True)),
                ('compliance_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('support_contract_identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_dns_name', models.CharField(blank=True, max_length=100, null=True)),
                ('password_owner', models.CharField(blank=True, max_length=20, null=True)),
                ('discovered_model', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('reporting', models.CharField(blank=True, max_length=20, null=True)),
                ('antivirus', models.CharField(blank=True, max_length=10, null=True)),
                ('discovered_os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('last_discovery_time', models.CharField(blank=True, max_length=20, null=True)),
                ('service_level_agreement', models.CharField(blank=True, max_length=10, null=True)),
                ('assignment_group', models.CharField(blank=True, max_length=50, null=True)),
                ('business_application', models.CharField(blank=True, max_length=150, null=True)),
                ('customer', models.CharField(blank=True, max_length=50, null=True)),
                ('calculated_location', models.CharField(blank=True, max_length=250, null=True)),
                ('running_software', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'unix_linux_act_full',
                'managed': False,
            },
        ),
    ]
